- name: install | create base directories
  file: path="{{ item }}" state=directory
  with_items:
    - "/opt/certbot"
    - "/var/.secrets/certbot"
    - "/etc/ssl/letsencrypt"
  tags: install

- name: install | clone certbot
  git:
    repo: "https://github.com/certbot/certbot.git"
    dest: "/opt/certbot"
    version: "master"
    update: "true"
    force: true
  tags: install

- name: install | set Certbot script variable.
  set_fact:
    certbot_script: "/opt/certbot/certbot-auto"
  tags: install

- name: install | ensure certbot-auto is executable
  file:
    path: "{{ certbot_script }}"
    mode: 0755
  tags: install

- name: install | install requirements
  apt:
    pkg:
      - python3-certbot-dns-ovh
      - python3-openssl
    state: present
  tags: install
